addons:
  apt:
    packages:
      - lib32stdc++6

env:
  global:
    - FLUTTER_CHANNEL=stable

cache:
  cocoapods: true
  directories:
  - $HOME/.pub-cache

if: branch = master 

install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get
script:
  - flutter pub run build_runner build
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --coverage --coverage-path=lcov.info
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: surge
  project: ./build/web
  domain: flutter-workshop.surge.sh
  on:
    branch: master
