language: generic
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
env:
  global:
    - FLUTTER_CHANNEL=stable
install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get
script:
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --coverage --coverage-path=lcov.info
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.pub-cache