# All Google internally enforced app development rules and some Flutter SDK development rules

# https://raw.githubusercontent.com/dart-lang/pedantic/master/lib/analysis_options.1.7.0.yaml
# https://github.com/flutter/flutter/blob/master/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    - always_declare_return_types # Flutter SDK style
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures # Flutter SDK style
    - camel_case_types # Flutter SDK style
    - cancel_subscriptions # Flutter SDK style
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - prefer_const_constructors # Flutter SDK style
    - prefer_const_constructors_in_immutables # Flutter SDK style
    - prefer_const_declarations # Flutter SDK style
    - prefer_const_literals_to_create_immutables # Flutter SDK style
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps # Flutter SDK style
    - unnecessary_const # Flutter SDK style
    - unnecessary_getters_setters # Flutter SDK style
    - unnecessary_new # Flutter SDK style
    - unnecessary_null_aware_assignments # Flutter SDK style
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides # Flutter SDK style
    - unnecessary_parenthesis # Flutter SDK style
    - unnecessary_statements # Flutter SDK style
    - unnecessary_this # Flutter SDK style
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps